version: "3.1"

services:
  seata-server:
    build:
      context: ./seata-server
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    networks:
      - seata
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - 13306:3306
    networks:
      - seata
    volumes:
      - /etc/localtime:/etc/localtime
      - ./scripts/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  seata:
    driver: bridge
